### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by genio** [pplu/perl-mssql-server#1]
Unfortunately, you can't just install DBD::OBDC without passing a flag to its Makefile.PL.

* ```cpan App::cpanminus```
* ```cpanm --look DBD::ODBC```
* ```perl Makefile.PL -u``` # enable [unicode](https://metacpan.org/pod/DBD::ODBC#Unicode) support
* ```make```
* ```make test```
* ```make install```

Until DBD::ODBC allows some sort of ENV variable, this is unfortunately necessary.

**Comment by genio** [comment]
https://github.com/perl5-dbi/DBD-ODBC/pull/6

I created a PR for that.

**Comment by pplu** [comment]
@genio : looks like this was solved on CPAN. 

How would you update the article to introduce unicode support?

**Comment by genio** [comment]
`DBD_ODBC_UNICODE=1; carton install`

That's all I'd really do
